language: java
jdk :  oraclejdk9
install: ./gradlew clean jar

env:
- COVERAGE=0
- COVERAGE=0.24
- COVERAGE=0.25
- COVERAGE=0.35
- COVERAGE=0.5

script: 
 
- ./gradlew -p ./monolithic/ui check
- ./gradlew -p ./monolithic/service/cart check
- ./gradlew -p ./monolithic/service/user check

- ./gradlew -p ./monolithic/repository/order check
- ./gradlew -p ./monolithic/repository/cart check
- ./gradlew -p ./monolithic/repository/product check
- ./gradlew -p ./monolithic/repository/user check
 
deploy:
 provider: script
 script: echo 'WFP'
 on:
   all_branches: true
   