language: java
jdk: oraclejdk9
install: "./gradlew clean jar"
services:
- docker
env:
  matrix:
  - COVERAGE=0
  - COVERAGE=0.24
  - COVERAGE=0.25
  - COVERAGE=0.35
  - COVERAGE=0.5
  global:
    - secure: "eA/DurZgcKCiylaQnZJqqC7aIeltx5mqGsjuUHKhXRLaRyTA1/Hm5KvbSIW1j8bIHRSy3xDmKjmk/TAHtTE4y9dGWa8ZEKi8JGKvB6XkgWjQ3NaAQ1nKZ4Vd9H9MM86MieFSewj2BJSPbxScmLoTXS9+RT0htiBWi9ZozaAoUdFHvgLYfneFZ4miKnCdxa9OxoiOBOFZixTy2hp7jSPca2fMvlQ+jHvcIuchnhEHTQaFR5v54FCnKQxW4qJdXagqK2N4N+Q4jEO8CpvGHoYR6hEQ6hAl1jafjUy7bL+p3O1rBV97iCOoAuEFho+7b7KMK46v4LEJN0tUq4gBmIVhBi0xTuwlnvyrRWL97zqzxkw73jK2rwMDbfGkt3wDp6Kc8fmfzPK85UmWBpwYRQP6qP42bwmTZ2h26tPoWj35qJ+m1xSAHFIrvrINaX3gRZnS3ytFAVcpAAD26/gvwvyCQ0P/gnmB1bTxPC7E6Sce4auKdn6H4bS0/IhQDiWwSyr59Z7kCorlhr0i+SDMfnn2+tJ8Jow6FeBhT2XokUZqLPnlJ+YXHFZGAt7DpEuNS3Jd1PcQdLIhsXCB2JIzgQnCh0DGmj5wz0EzIFa7kJu8jnB0mO+fzvRKUk55XPxpGL+jQos+TeJk31zPvXdz2BDwmuSEgspkiy9wS8JAdGn39QI="
    - secure: "Ti6LTBWtpLqJ+ajotA+/zgpULX1XyvdPTyW8L/qahrAwZG5aeyYtGe2rz/+00TEKOX1fMQBKqTpJR7s9UqEZ68/YW+RLUsNZxG8JMw15qCqq1iCO+1lfeaqwUtCegi7npuwaFCm++k7YnyqcZpeY1Z/GCaL+Oe5mdDyZ9xWa7PfbosJGRR2EVbKIK35wY49sZWkliMBPH06zRsnru4DiDpXBhWzn53fbfg8xnB3TEGkMrV50OxNBSnAWIA9MwHzlQgPnD1JAnUZlr5MsvwCBlmQBXJnCqd+Ji5FLhD7OplXm4CE8AmsrVGK3B4cvWOz9ZXRdoPr/tMS6gOx5GiOsb+Eu5QKstSgEzLJGU730Hnq8oVvQjRBtgUSR4pzM+HhzCwPPjKt34THCpqhav5lAQMAETNrb4dvw4ZOpOLfS5AwCe9MkVPNVv3ykeWhsbzPk6qu0dxjMKae2X5UE4uPhZuV7LAm2vXnDpFaScVCVzXV8ITlVOZCdkNB6TIcEWJUkL/nTYSAmUHlQA5ZQvLNWqmpCB02x3i+hfx2oMdb1N6uYNfxTRPig+HN9IErhoRixFkfUuk/bp8EFQY0r46TCLdBPVN+paDS7jZhORt6W31nEMph7Xjir+6hBkpiKhUom5dcE+uCCyb76AkbeQWCgFQmMLMUtu8qSPalq94kZb2o="
    script:
      - "./gradlew -p ./monolithic/ui check"
      - "./gradlew -p ./monolithic/service/cart check"
      - "./gradlew -p ./monolithic/service/user check"
      - "./gradlew -p ./monolithic/repository/order check"
      - "./gradlew -p ./monolithic/repository/cart check"
      - "./gradlew -p ./monolithic/repository/product check"
      - "./gradlew -p ./monolithic/repository/user check"
      deploy:
        provider: script
        script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\"
          --password-stdin"
        on:
          all_branches: true
          